// Nombres en español por id de producto. La API (dummyjson) solo devuelve inglés.
// Los productos que son solo marca/modelo (p. ej. "iPhone X") conservan su nombre original.
export const productNamesEs = {
  1: 'Máscara de pestañas Essence Lash Princess',
  2: 'Paleta de sombras con espejo',
  3: 'Polvera compacta',
  4: 'Labial rojo',
  5: 'Esmalte de uñas rojo',
  6: 'Calvin Klein CK One',
  7: 'Chanel Coco Noir Eau de Parfum',
  8: "Dior J'adore",
  9: 'Dolce Shine Eau de Parfum',
  10: 'Gucci Bloom Eau de Parfum',
  11: 'Cama Annibale Colombo',
  12: 'Sofá Annibale Colombo',
  13: 'Mesa de noche de cerezo africano',
  14: 'Silla ejecutiva de conferencias Knoll Saarinen',
  15: 'Lavamanos de madera con espejo',
  16: 'Manzana',
  17: 'Filete de res',
  18: 'Comida para gatos',
  19: 'Carne de pollo',
  20: 'Aceite de cocina',
  21: 'Pepino',
  22: 'Comida para perros',
  23: 'Huevos',
  24: 'Filete de pescado',
  25: 'Pimiento verde',
  26: 'Ají verde',
  27: 'Frasco de miel',
  28: 'Helado',
  29: 'Jugo',
  30: 'Kiwi',
  31: 'Limón',
  32: 'Leche',
  33: 'Mora',
  34: 'Café Nescafé',
  35: 'Papas',
  36: 'Proteína en polvo',
  37: 'Cebollas moradas',
  38: 'Arroz',
  39: 'Gaseosas',
  40: 'Frutilla',
  41: 'Caja de pañuelos desechables',
  42: 'Agua',
  43: 'Columpio decorativo',
  44: 'Portarretrato árbol genealógico',
  45: 'Planta decorativa para el hogar',
  46: 'Maceta',
  47: 'Lámpara de mesa',
  48: 'Espátula de bambú',
  49: 'Taza de aluminio negra',
  50: 'Batidor negro',
  51: 'Licuadora en caja',
  52: 'Wok de acero al carbono',
  53: 'Tabla de picar',
  54: 'Exprimidor de cítricos amarillo',
  55: 'Cortador de huevos',
  56: 'Cocina eléctrica',
  57: 'Colador de malla fina',
  58: 'Tenedor',
  59: 'Vaso',
  60: 'Rallador negro',
  61: 'Batidora de mano',
  62: 'Cubetera para hielo',
  63: 'Tamiz de cocina',
  64: 'Cuchillo',
  65: 'Lonchera',
  66: 'Horno microondas',
  67: 'Soporte para tazas',
  68: 'Sartén',
  69: 'Plato',
  70: 'Pinzas rojas',
  71: 'Olla plateada con tapa de vidrio',
  72: 'Espátula ranurada',
  73: 'Especiero',
  74: 'Cuchara',
  75: 'Bandeja',
  76: 'Rodillo de madera',
  77: 'Pelador amarillo',
  78: 'Apple MacBook Pro 14 pulgadas gris espacial',
  79: 'Laptop Asus Zenbook Pro de doble pantalla',
  80: 'Huawei Matebook X Pro',
  81: 'Lenovo Yoga 920',
  82: 'Nueva laptop DELL XPS 13 9300',
  83: 'Camisa a cuadros azul y negra',
  84: 'Polera de hombre Gigabyte Aorus',
  85: 'Camisa escocesa de hombre',
  86: 'Camisa de manga corta de hombre',
  87: 'Camisa a cuadros de hombre',
  88: 'Nike Air Jordan 1 rojo y negro',
  89: 'Tacos de béisbol Nike',
  90: 'Zapatillas Puma Future Rider',
  91: 'Zapatillas deportivas blanco hueso y rojo',
  92: 'Zapatillas deportivas blanco hueso rojo',
  93: 'Reloj con correa de cuero marrón',
  94: 'Longines Master Collection',
  95: 'Rolex Cellini Date esfera negra',
  96: 'Rolex Cellini Moonphase',
  97: 'Rolex Datejust',
  98: 'Reloj Rolex Submariner',
  99: 'Amazon Echo Plus',
  100: 'Apple AirPods',
  101: 'Apple AirPods Max plateados',
  102: 'Cargador inalámbrico Apple AirPower',
  103: 'Apple HomePod Mini gris cósmico',
  104: 'Cargador de iPhone Apple',
  105: 'Batería Apple MagSafe',
  106: 'Apple Watch Series 4 dorado',
  107: 'Audífonos inalámbricos Beats Flex',
  108: 'Funda de silicona para iPhone 12 con MagSafe color ciruela',
  109: 'Monopié',
  110: 'Lámpara para selfies con iPhone',
  111: 'Palo selfie monopié',
  112: 'Pedestal para cámara de estudio de TV',
  113: 'Motocicleta genérica',
  114: 'Kawasaki Z800',
  115: 'MotoGP CI.H1',
  116: 'Motoneta',
  117: 'Motocicleta deportiva',
  118: 'Jabón de manos Attitude Super Leaves',
  119: 'Gel de ducha Olay Ultra Moisture con manteca de karité',
  120: 'Loción corporal y facial Vaseline Men',
  121: 'iPhone 5s',
  122: 'iPhone 6',
  123: 'iPhone 13 Pro',
  124: 'iPhone X',
  125: 'Oppo A57',
  126: 'Oppo F19 Pro Plus',
  127: 'Oppo K1',
  128: 'Realme C35',
  129: 'Realme X',
  130: 'Realme XT',
  131: 'Samsung Galaxy S7',
  132: 'Samsung Galaxy S8',
  133: 'Samsung Galaxy S10',
  134: 'Vivo S1',
  135: 'Vivo V9',
  136: 'Vivo X21',
  137: 'Balón de fútbol americano',
  138: 'Pelota de béisbol',
  139: 'Guante de béisbol',
  140: 'Balón de básquetbol',
  141: 'Aro de básquetbol',
  142: 'Pelota de críquet',
  143: 'Bate de críquet',
  144: 'Casco de críquet',
  145: 'Palos de críquet (wicket)',
  146: 'Volante de plumas para bádminton',
  147: 'Balón de fútbol',
  148: 'Pelota de golf',
  149: 'Palo de golf de hierro',
  150: 'Bate de béisbol metálico',
  151: 'Pelota de tenis',
  152: 'Raqueta de tenis',
  153: 'Balón de vóleibol',
  154: 'Lentes de sol negros',
  155: 'Lentes de sol clásicos',
  156: 'Lentes verde y negro',
  157: 'Lentes de fiesta',
  158: 'Lentes de sol',
  159: 'iPad Mini 2021 blanco estelar',
  160: 'Samsung Galaxy Tab S8 Plus gris',
  161: 'Samsung Galaxy Tab blanca',
  162: 'Vestido azul',
  163: 'Vestido de verano para niña',
  164: 'Vestido gris',
  165: 'Vestido corto',
  166: 'Vestido escocés',
  167: 'Chrysler 300 Touring',
  168: 'Dodge Charger SXT RWD',
  169: 'Dodge Hornet GT Plus',
  170: 'Dodge Durango SXT RWD',
  171: 'Chrysler Pacifica Touring',
  172: 'Cartera azul de mujer',
  173: 'Bolso de cuero de mujer Heshe',
  174: 'Bolso de mujer Prada',
  175: 'Mochila blanca de cuero sintético',
  176: 'Cartera negra de mujer',
  177: 'Vestido de gala negro',
  178: 'Corsé de cuero con falda',
  179: 'Corsé con falda negra',
  180: 'Vestido Pea',
  181: 'Traje Marni rojo y negro',
  182: 'Arete de cristal verde',
  183: 'Arete ovalado verde',
  184: 'Arete tropical',
  185: 'Pantuflas negras y marrones',
  186: 'Zapatos de tacón Calvin Klein',
  187: 'Zapatos dorados de mujer',
  188: 'Zapatos Pampi',
  189: 'Zapatos rojos',
  190: 'IWC Ingenieur automático de acero',
  191: 'Rolex Cellini Moonphase',
  192: 'Rolex Datejust de mujer',
  193: 'Reloj dorado de mujer',
  194: 'Reloj de pulsera de mujer',
}
